### ISSUE TITLE
Icarus template, Name of the Server Instance

### ISSUE THREAD

**Issue by Grass5k** [patrix87/PowerShellGSM#13]
The template has the below:
    #Name of the Server Instance
    Name = $Name

Might be better to understand if it was this:
    #Name of the Server Instance
    Name = "Name"

**Comment by patrix87** [comment]
$Name is a variable that is defined earlier in the config.
"Name" is the string Name.
You do not have to change configurations past the first section of the file.
They are there so you can do it if you know what you're doing.

**Comment by Grass5k** [comment]
Thanks I'll take another look must have missed it.

________________________________
