### ISSUE TITLE
Request: Log Cleanup

### ISSUE THREAD

**Issue by vikadev** [patrix87/PowerShellGSM#15]
First off, thank you for this script! It's awesome.

Just wanted to throw in a suggestion of allowing the user to set how long they want to keep the logs for (maybe in days) and then have the script do some cleanup. I had an issue with the process lock and generated almost 20,000 logs in the span of a week or so.

Great work and thanks again!

-M

**Comment by ConnectivityChris** [comment]
@vikadev 
You can set server log limit in the global config
https://github.com/patrix87/PowerShellGSM/blob/main/global.psm1#L17

**Comment by patrix87** [comment]
I'm looking into a fix to exclude state checks from the logs. since those run every two minutes.

**Comment by patrix87** [comment]
This is fixed in the last release

**Comment by vikadev** [comment]
Thank you both for this! Sorry about getting back to you so late!
