### ISSUE TITLE
Looking for Beta Version

### ISSUE THREAD

**Issue by cayeman01** [patrix87/PowerShellGSM#16]
Not sure if I am the only one, but the steam installer is looking for a beta version which is no longer out there.  I was able to get past it by running steamcmd manually and leaving off the -beta switches.  Everything else is good so far.

**Comment by patrix87** [comment]
Hi, are you talking about a specific template ?

**Comment by cayeman01** [comment]
Excellent work with these files / process!

Icarus.  When going through the launcher and which connects to the powershell file, it was erroring because it was looking for some beta flags.  I could not figure out where to turn that off.  I commented out the beta password fields, but that did not help.  See screen shots below.

I was able to run steamcmd separately and install Icarus Dedicated server, then your process worked from there.

[A screenshot of a computer  Description automatically generated with medium confidence]

***@***.***

**Comment by patrix87** [comment]
I think it fixed the issue in the last release [#3.0.1](https://github.com/patrix87/PowerShellGSM/releases/tag/3.0.1)

The Steam servers have been unstable latelly and steamCMD update and download randomly fail for some games.

The update added a check and retry that eventually get the job done.

**Comment by cayeman01** [comment]
Thank you!
