### ISSUE TITLE
Stationeers Not working

### ISSUE THREAD

**Issue by PantACRO4life** [patrix87/PowerShellGSM#17]
I know this game is picky but lunching it with this manager it doesnt work at all. I ended up creating a batch file un the server folder where live "rocketstation_DedicatedServer.exe"

**Comment by patrix87** [comment]
I no longer have the game so it will be hard for me to test that, but you should be able to modify the launch command directly in the psm1 config file which should give you the same results.
Then if it work feel free to open a pull resquest.
Thanks

**Comment by patrix87** [comment]
Please put that in a code block. Thanks

**Comment by PantACRO4life** [comment]
Updated
