### ISSUE TITLE
Incorrect task priority assignment.

### ISSUE THREAD

**Issue by TOXid** [patrix87/PowerShellGSM#19]
When specifying a two-word priority value, for example Above Normal, neither priority assignment nor affinity works.
It is also necessary to assign affinity when starting the server, and not after the server is fully started. Because when loading, the server consumes resources from other applications. Also in this case it works slower due to the assignment to another Numa node.

ark survival ascended

**Comment by patrix87** [comment]
I'll check for the 2 words issue, but the priority assignment after launch is normal, some games will have a launch process and a run process. We want the actual server to be at that priority, not the launcher.

**Comment by patrix87** [comment]
AboveNormal is the correct way to write the 2 word value.
I updated the comment, this will be in the next release.
