### ISSUE TITLE
ServerAdminPassword in gus.ini is adding other arguments to end of password value

### ISSUE THREAD

**Issue by chenry0553** [patrix87/PowerShellGSM#20]
i've deleted the installation and started from scratch twice. both times i've only used the ASE.psm1 script in configs to update server information. servers is running without errors being thrown, although I haven't seen the server on the list due to some port forwarding issues most likely. when i look at gameusersettings.ini I see that about half of the command line argument is being added to the serveradminpassword string for some reason. it is adding port, query port, rcon port, serverPVE, etc, when it shouldn't be. love the script so far, any help appreciated

**Comment by patrix87** [comment]
I have to merge PR #18 that is related to that issue. I did not have the time to do it yet.

**Comment by patrix87** [comment]
Can you validate if you're still seeing this issue today ?
