### ISSUE TITLE
Ark survival ascended server: Max player settings 

### ISSUE THREAD

**Issue by TOXid** [patrix87/PowerShellGSM#26]
It looks like the old command `?MaxPlayers=100` doesn't work, you need to use this argument `-WinLiveMaxPlayers=100`.

**Comment by Sephodious** [comment]
That's already included in the file. 

`  #Maximum Number of Players
  MaxPlayers             = 10`
  
  and further down it calls it 
  
  `$ArgumentList += " -WinLiveMaxPlayers=$($Server.MaxPlayers)" #Fix MaxPlayers not working.`
