### ISSUE TITLE
Conan Exiles

### ISSUE THREAD

**Issue by Aeneas1** [patrix87/PowerShellGSM#29]
I wrote a template for "Conan Exiles" which works fine for me, but please look for mistakes and add it to your repository if you wish.
(.txt cause .psm1 cant be uploaded)

[conan_exiles.txt](https://github.com/patrix87/PowerShellGSM/files/13310227/conan_exiles.txt)

**Comment by patrix87** [comment]
Fork the repository and submit a pull request please.
