### ISSUE TITLE
Ark survival ascended server: daily reboot problem

### ISSUE THREAD

**Issue by TOXid** [patrix87/PowerShellGSM#32]
Automatic daily reboot does not work if the warning time is set to be greater than the task update time.

`Timers     = [System.Collections.ArrayList]@(1140, 600, 60)`

With such a timer, the server sends only the first warning to the chat and then the next time the task is launched in the scheduler, it simply sets a new reboot time without completing the current task.

```
Verifying Dependencies...
Importing Server Configuration...
Locking Process.
Running Tasks for ark_survival_ascended ...
Getting Tasks Schedule...
Checking Alive State
Server is Alive
Updating Tasks Schedule...
Too soon for Update check
Server is due for Restart
Updating Tasks Schedule...
Verifying Server installation...
Verifying Server State...
Command Sent.
Server is responding to remote messages.
Server is running, warning users about upcomming restart.
Command Sent.
Waiting 1140 seconds before next warning...
```

This stops the execution of the script.

> Edit this value :
> 
> https://github.com/patrix87/PowerShellGSM/blob/98dfc698cc8bc6558f9947bfc967d9f813d92095/global.psm1#L48

It did not help. It looks like the reboot script simply stops working after 5 minutes, or when the task starts.
I set the reboot to 5:00.
At 5:00
```
Verifying Dependencies...
Importing Server Configuration...
Locking Process.
Running Tasks for ark_survival_ascended ...
Getting Tasks Schedule...
Too soon for Alive check
Too soon for Update check
Server is due for Restart
Updating Tasks Schedule...
Verifying Server installation...
Verifying Server State...
Command Sent.
Server is responding to remote messages.
Server is running, warning users about upcomming restart.
Command Sent.
Waiting 1140 seconds before next warning...
```
And then every 5 minutes for a 35 minute lock:

```
**********************
PS>TerminatingError(): "System error."
**********************
```
The daily reboot cycle never completed. So at some point the reboot script simply stops working, perhaps you need to initialize the launch of the run.cmd file, it reboots correctly with a 30-minute cooldown.

Auto-update with the same problem.

**Comment by patrix87** [comment]
Set the LockTimeout to a value that is higher than your reboot cycle time.
Right now your reboot cycle takes a whole 30 minutes (which I think is very exaggerated)
Then set the LockTimeout to 35 minutes or 60 minutes.

**Comment by TOXid** [comment]
The blocking was set for 35 minutes, but apparently the script stopped working after 5 minutes, when a new task was launched in the task manager. There was only the first warning about 30 minutes in the chat. If it were a matter of insufficient blocking time, then at least there would be a second message about 10 minutes. But in the chat every 40 minutes there was only a message about 30 minutes before the restart, when the server was trying to update.

Regarding the long time - this is necessary for this game, since players cannot leave a cave or boss in 5 minutes, and this is guaranteed to lead to the loss of all equipment and dinos.

**Comment by patrix87** [comment]
I'm not sure what is the issue on your side but the auto-restart seems to be working on my side. Look into the ASA Logs for the server log. You should see the restart there.

**Comment by TOXid** [comment]
Have you tried setting the restart time to 30 minutes?
At 5 minutes everything works for me, at 30 minutes only the first message is sent to the chat.

**Comment by duartejbrito** [comment]
I'm having exactly the same issue

**Comment by TOXid** [comment]
I found the problem, it is in the file Register-Task.psm1

**Comment by simonghpub** [comment]
Care to share the solution or details then?
