### ISSUE TITLE
Ark survival ascended server: Problem with running the server twice.

### ISSUE THREAD

**Issue by TOXid** [patrix87/PowerShellGSM#35]
Tell me how to check the stability of the server? I encountered a problem that after restarting for the update, two copies of the server started up with an interval of 20 minutes.

**Comment by TOXid** [comment]
The double start problem appeared several times. After a reboot, the script considers the server dead and starts a new copy. How will the server be checked at startup? Could the problem be due to the fact that Rcon is using another service at this moment?

**Comment by simonghpub** [comment]
When the script attempts to start the server it creates a .lock file in the servers folder, the lock file gets removed when it has determined that the server is in fact running. If the lock file doesn't get removed for some reason it will automatically be removed after 30 minutes (line 48 in global.psm).

After the reboot you mentioned, did you by any chance start the server yourself before the job in the task scheduler kicks in?

**Comment by TOXid** [comment]
> When the script attempts to start the server it creates a .lock file in the servers folder, the lock file gets removed when it has determined that the server is in fact running. If the lock file doesn't get removed for some reason it will automatically be removed after 30 minutes (line 48 in global.psm). The presence of the .lock file prevents the script from starting any further processes.
> 
> After the reboot you mentioned, did you by any chance start the server yourself before the job in the task scheduler kicks in?

No, it was an automatic server restart during the update. I noticed that neither affinity nor priority was applied on the first copy.
