### ISSUE TITLE
Ark survival ascended server: Start Error 

### ISSUE THREAD

**Issue by BlackWolf12019** [patrix87/PowerShellGSM#36]
When running run.cmd

Setting Script Directory as Working Directory...
Working Directory : E:\PowerShellGSM
Finding server IPs...
xxxxxxx
Verifying Dependencies...
Importing Server Configuration...
Process is locked, exiting.

PS>TerminatingError(): "System Error."

+If launch several maps, the already running one closes

**Comment by TOXid** [comment]
I think your problem is that you are trying to run several servers with one config.
For this reason, your process got locked after the script execution was interrupted. Delete the lock file.

**Comment by BlackWolf12019** [comment]
> I think your problem is that you are trying to run several servers with one config. For this reason, your process got locked after the script execution was interrupted. Delete the lock file.

The files in the configs folder have different names. They match the names in the launchers folder. When launching several servers for one game, should the configuration and launch files be different in some way except the name and paths for saving the files?

**Comment by BlackWolf12019** [comment]
The reason was a modified variable that did not need to be changed =)
