### ISSUE TITLE
Ark: Survival Ascended server not showing up on list

### ISSUE THREAD

**Issue by greggmcgarrity** [patrix87/PowerShellGSM#37]
I'm not 100% sure what the issue is, if this is an issue with my VPS, an issue with SteamCMD or an issue with PowerShellGSM (i'd assume one of the first two)...

I had a server up and running perfectly fine until I hadn't been on for a while and logged in to my VPS to see that it had restarted at some point and the server was no longer running. I ran the launcher again and waited on it booting up (everything looked fine) but nothing showed up in the server list.

I have downloaded CurrPorts to see what ports are showing for ArkAsendedServer and I currently see 27020 and 8888 under TCP with a State "Listening" and I can see 7777 under UDP but there is no state".

I'm really know nothing about networking so any advice/help would be appreciated.

Note: I have contacted the company I bought my VPS off of and they have basically told me there's nothing they can do...

**Comment by TOXid** [comment]
This problem is not related to PowerShellGSM. It doesn't do port forwarding, you have to do that yourself.

**Comment by greggmcgarrity** [comment]
I have since found that this was a Windows Server issue in that you need to manually install trust certificates for it to authenticate with the Epic servers if you have crossplay enabled (from what I've read). The trust certificates in question are [Trust Certificate 1](https://www.amazontrust.com/repository/AmazonRootCA1.cer) and [Trust Certificate 2](http://crt.r2m02.amazontrust.com/r2m02.cer).
