### ISSUE TITLE
Ark: Survival Ascended server API

### ISSUE THREAD

**Issue by BlackWolf12019** [patrix87/PowerShellGSM#38]
Please add launch via AsaApiLoader.exe https://gameservershub.com/forums/resources/ark-survival-ascended-serverapi-crossplay-supported.683/

**Comment by simonghpub** [comment]
Don't know that software but seems like you just need to change what executable to run.
From the page you linked to:

> You must launch "AsaApiLoader.exe" next. The loader must be launched as if it was the ArkAscendedServer.exe (with the same parameters). Once launched the api will start and server will be launched too.


The Exec setting, line 100 in the template:
`  Exec                   = ".\servers\$Name\ShooterGame\Binaries\Win64\ArkAscendedServer.exe"`

**Comment by BlackWolf12019** [comment]
> Don't know that software but seems like you just need to change what executable to run. From the page you linked to:
> 
> > You must launch "AsaApiLoader.exe" next. The loader must be launched as if it was the ArkAscendedServer.exe (with the same parameters). Once launched the api will start and server will be launched too.
> 
> The Exec setting, line 100 in the template: ` Exec = ".\servers\$Name\ShooterGame\Binaries\Win64\ArkAscendedServer.exe"`


The API was updated and the problem disappeared, thanks for the answer
