### ISSUE TITLE
Icarus Server errors and shutdown constantly

### ISSUE THREAD

**Issue by Runaris** [patrix87/PowerShellGSM#43]
I am unsure what's going on here but its only affecting my Icarus Server after weekly update 108 hotfix. Server will start, but will only stay up for a very short amount of time (about 3minutes) before the client checks the server and it just automatically crashes sending it into a boot loop (where the scheduler will go round in circles because it crashed) Haven't been able to cleanly host it since using this really handy program.

**Comment by Torath0071** [comment]
Hi, i've the same issue.

And i found a solution to the problem (i will make a pull request for that)

In the file main.ps1 make these changes

Line 115 : if (($Server.AutoRestartOnCrash) -and ((New-TimeSpan -Start Get-Date -End $TasksSchedule.NextAlive) -le 0)) {
Line 130 : if (($Server.AutoUpdates) -and ((New-TimeSpan -Start Get-Date -End $TasksSchedule.NextUpdate) -le 0)) {
Line 145 : if (($Server.AutoRestart) -and ((New-TimeSpan -Start Get-Date -End $TasksSchedule.NextRestart) -le 0)) {

The problem arose from the fact that the date of the next update was compared with the current date 01/01/2024 is less than 12/31/2023 (compared values) and therefore launches a full update.

**Comment by TOXid** [comment]
> Line 115 : if (($Server.AutoRestartOnCrash) -and ((New-TimeSpan -Start Get-Date -End $TasksSchedule.NextAlive) -le 0)) {

![1](https://github.com/patrix87/PowerShellGSM/assets/19214819/9e5a5a09-d4b1-4b63-97e5-fab251a986ea)
It's not working....

**Comment by Torath0071** [comment]
Oh yes, sorry, I'm not really familiar with Powershell. 
Try to surround Get-Date like this  (Get-Date) 

Line 115 : if (($Server.AutoRestartOnCrash) -and ((New-TimeSpan -Start (Get-Date) -End $TasksSchedule.NextAlive) -le 0)) {
Line 130 : if (($Server.AutoUpdates) -and ((New-TimeSpan -Start (Get-Date) -End $TasksSchedule.NextUpdate) -le 0)) {
Line 145 : if (($Server.AutoRestart) -and ((New-TimeSpan -Start (Get-Date) -End $TasksSchedule.NextRestart) -le 0)) {

**Comment by TOXid** [comment]
> Oh yes, sorry, I'm not really familiar with Powershell.
> Try to surround Get-Date like this (Get-Date)

No, it still doesn’t work, there’s some kind of system time conversion error. I don’t have time to read and screenshot.

**Comment by patrix87** [comment]
Should be resolved in [latest release](https://github.com/patrix87/PowerShellGSM/releases/tag/3.3)
