### ISSUE TITLE
Restart loop - New Year Date

### ISSUE THREAD

**Issue by Haidies-AU** [patrix87/PowerShellGSM#45]
Server and script have been running flawlessly for months.
Today the server has been restarting every 10 minutes since its 4am restart.
each log file showing the script thinks the server is due for a restart.

NextRestart: 01/01/2024

I suspect the script is only using the day and month, 
Since those two values are now less than current it believes it needs to restart.

**Comment by Haidies-AU** [comment]
Now that its past midnight the problem has resolved, I have no doubt it will return next New Years Eve.

**Comment by Torath0071** [comment]
Hi, you can check a fix here 
https://github.com/patrix87/PowerShellGSM/issues/43#issuecomment-1872971511

Pull request already exists to fix this bug :)

**Comment by patrix87** [comment]
Should be resolved in [latest release](https://github.com/patrix87/PowerShellGSM/releases/tag/3.3)
