### ISSUE TITLE
Maybe Change requirements

### ISSUE THREAD

**Issue by padesmo** [patrix87/PowerShellGSM#48]
Hi, today i installed a new Windows Machine, i got the VCRUNTIME.dll not existing errors. 
After installing the Visual C++ Redistributable it works just fine.

Where i downloaded:
https://learn.microsoft.com/de-DE/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by patrix87** [comment]
It's the reponsability of the game server to validate and provide or install dependencies. I can't possibly maintain that for them.
