### ISSUE TITLE
Updating PaperMC

### ISSUE THREAD

**Issue by Momonga2** [patrix87/PowerShellGSM#49]
I might have missed something, but how do we update PaperMC to the latest version? It's currently on version 1.17.1. In the Paperclip config I've set the update automatically option to true. However, when running the server it's not looking for updates. I tried updating it manually but the server fails to start (works again once changes are reverted).

**Comment by patrix87** [comment]
You need to update those [links](https://github.com/patrix87/PowerShellGSM/blob/5cf56cdf579a4230f7f6493ac2f3d71ad49784d8/templates/paperclip.psm1#L72-L76) : 
Paperclip does not recommend doing auto-updates and does not provide any API to check for updates.
