### ISSUE TITLE
Error invoke-webrequest to get external IP

### ISSUE THREAD

**Issue by Moubai** [patrix87/PowerShellGSM#5]
Hello,
i Get this error when i launch the script for satisfactory

> Invoke-WebRequest : Le contenu de la réponse ne peut pas être analysé, car le moteur d’Internet Explorer n’est pas
> disponible ou la configuration du premier lancement d’Internet Explorer n’est pas complète. Spécifiez le paramètre
> UseBasicParsing et réessayez.
> Au caractère D:\server\PowerShellGSM-2.6.6\functions\network\Set-IP.psm1:9 : 20
> +     $ExternalIP = (Invoke-WebRequest ifconfig.me/ip).Content.Trim()
> +                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotImplemented: (:) [Invoke-WebRequest], NotSupportedException
>     + FullyQualifiedErrorId : WebCmdletIEDomNotSupportedException,Microsoft.PowerShell.Commands.InvokeWebRequestComman
>    d
> 

Internet explorer is not initialized, (i've never launch internet explorer on this windows, and when we launch it now it launch Edge instead)

i've modified the cmd to use -UseBasicParsing it work well

    #Get current external ip from ifconfig.me
    $GetIP= Invoke-WebRequest ifconfig.me/ip -UseBasicParsing
    $ExternalIP = $GetIP.Content.Trim()

[Set-IP.txt](https://github.com/patrix87/PowerShellGSM/files/7463601/Set-IP.txt)

**Comment by patrix87** [comment]
Do you have Internet Explorer installed or enabled on the server ?

**Comment by patrix87** [comment]
Oh sorry I read too fast, I'll test it and add it to the next release then.

**Comment by Moubai** [comment]
it was on windows 10 21h1, pretty sure we can reproduce the pb on a fresh VM

**Comment by patrix87** [comment]
Fixed in last release.
