### ISSUE TITLE
Errors on first run/setup.

### ISSUE THREAD

**Issue by Depictionx** [patrix87/PowerShellGSM#52]
When running the launcher palworld.cmd. Powershell will open and start as expected. Start installing and then error out on 'Importing Server Configuration...'

Downloading ARRCON.
ARRCON Installed.
Downloading SteamCMD.
SteamCMD Installed.
Downloading mcrcon.
Mcrcon Installed.
Importing Server Configuration...
MaxPlayers : The term 'MaxPlayers' is not recognized as the name of a cmdlet, function, script file, or operable 
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\PowerShellGSM\PowerShellGSM-main\configs\palworld.psm1:32 char:3
+   MaxPlayers         = 32
+   ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (MaxPlayers:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException
MaxPlayers : The term 'MaxPlayers' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
[2024-01-25_23-26-40-palworld.txt](https://github.com/patrix87/PowerShellGSM/files/14060320/2024-01-25_23-26-40-palworld.txt)

**Comment by Depictionx** [comment]
Turns out if you delete your quotations on the password field, instead of just the CHANGEME within them, it causes this...

**Comment by patrix87** [comment]
Yeah you need to leave the quotation marks on all strings in powershell. Otherwise it tries to interpret that as a command.

**Comment by Depictionx** [comment]
Yup! I had been working at some stuff for about 5-6 hours before I found your GSM. I didn't mean to delete the quotation marks.
