### ISSUE TITLE
Ark ASA servers duplicating

### ISSUE THREAD

**Issue by Mitchell-V** [patrix87/PowerShellGSM#54]
Hi there,

I've been using your scripts for a while now and, whilst most of the stuff is running perfectly fine, I do encounter a random issue. Sometimes the script fails to recognize that a server already exists and boots up a duplicate server using the same set up. This causes many headaches as 2 servers writing to the same files often lead to corruption of people's stuff in-game. I was wondering if there's a way to prevent this from happening. I included a screenshot of an error that I see pop up occasionally when trying to reboot the servers. The dupe issue is often the consequence of this error. Thank you in advance for the assistance!

![image](https://github.com/patrix87/PowerShellGSM/assets/43780830/47037408-d352-45bb-8798-9ba564ca6044)

**Comment by patrix87** [comment]
Can you send me some logs of when the error occured ?

**Comment by Mitchell-V** [comment]
Certainly! Here is a log file of when that bug occurred during runtime. I hope this helps and if you need more info please let me know!
[2024-03-03_17-15-01-ark_survival_ascended_Svart.txt](https://github.com/patrix87/PowerShellGSM/files/14497929/2024-03-03_17-15-01-ark_survival_ascended_Svart.txt)

**Comment by patrix87** [comment]
You're using \ShooterGame\Binaries\Win64\AsaApiLoader.exe instead of the intended Executable.
This is executable is not supported as it launches a second process.

**Comment by Mitchell-V** [comment]
Thank you for your reply!

The executable I am using is part of the server API that allows the server to run plugins. It is quite a popular API with incredibly useful utility for servers/server owners. I understand that you may not want to add built-in support for this API executable or that it may not even be possible, but I think I'm not the only one who would advocate for that if it were to be possible and it could be very useful to have for your amazing scripts.

I will look elsewhere for other solutions to automating ark's server managing as I cannot run the cluster without the API. Once again thank you for your support!
