### ISSUE TITLE
User was able to join without password.

### ISSUE THREAD

**Issue by EnviroGuy** [patrix87/PowerShellGSM#55]
Hi there! recently I had an issue where a user was able to join my Icarus server without being required to enter the password configured in the configuration script (icarus.psm1>Password =).  

I reviewed the logs and was unable to determine why, nor was I able to identify any malicious activity by the user. 

There are over 100k lines in the log so I'm not sure what to share. :)

**Comment by patrix87** [comment]
Share the script log, not the game log

**Comment by EnviroGuy** [comment]
The issue has been resolved. It was a configuration error on my part.
________________________________
