### ISSUE TITLE
PalWorld - ProcessName changed

### ISSUE THREAD

**Issue by BananaAcid** [patrix87/PowerShellGSM#56]
https://github.com/patrix87/PowerShellGSM/blob/496499137784ea0260f16fe99278fbacb3b2ff34/templates/palworld.psm1#L81

has become `"PalServer-Win64-Shipping-Cmd"` on 04 APR 2024

**Comment by BananaAcid** [comment]
BTW: since it could not find the process, the scheduled task restarted all 5 min and created backups each time until my server drive was maxed out.

**Comment by patrix87** [comment]
@BananaAcid I'm super busy with work until this fall, would you be ready to be added as a contributor so you can take care of issues and pull request ?

**Comment by BananaAcid** [comment]
@patrix87 Sure, I am happy to help. Even better: on something I use myself :)

**Comment by patrix87** [comment]
@BananaAcid Add me on Discord. I don't have an official PowerShellGSM Discord, but I can make a group chat for now.

Username: patrix

**Comment by patrix87** [comment]
I created a Discord Server: https://discord.gg/ShTtk6RHYQ

It is very basic right now, but if others want to join.

**Comment by TheJoshuaTerry** [comment]
Any news on when this change will be made? It still set to Test not Shipping

**Comment by patrix87** [comment]
The fix was merge into main.
