### ISSUE TITLE
[Documentation] Comment about how to let the servers run like a service (in bg)

### ISSUE THREAD

**Issue by BananaAcid** [patrix87/PowerShellGSM#58]
I could not find a comment on how to let the servers start after a system restart, but luck had it, I only needed the chane the scheduler task from "Run only when user is logged on" to "Run when user is logged on or not" and enter the specific user's password. 

having that in the docs would be great

![image](https://github.com/patrix87/PowerShellGSM/assets/1894723/ae15a500-4ccb-4ca3-8959-60de9ecb078c)

**Comment by patrix87** [comment]
Would this work with any game servers ?
What platform was this tested on ?
Did it had a password ?

**Comment by BananaAcid** [comment]
Yes this would work with any.

This method is available since WindowsXP, and I used it since then quite frequently. Currently running on Win10 Pro, Win11 Pro, Windows Server 2008, Windows Server 2024.

User-Accounts all had a password, always.

**Comment by patrix87** [comment]
That can't be automated as the user passwords needs to be entered.
