### ISSUE TITLE
Satisfactory - update - questions about experimantal server

### ISSUE THREAD

**Issue by Moubai** [patrix87/PowerShellGSM#6]
Hello,
so the update 5 is now on the Early access Branch for satisfactory, if a user want to launch the Experimental branch server, it must be add
this parameter "-beta experimental"
full cmd = "steamcmd.exe +login anonymous +force_install_dir C:\GameServers\SatisfactoryServer +app_update 1690800 -beta experimental validate +quit"

so is it better to make a new powershell config file to have the 2 releases or a this variable in the conf file ? 
"#Name of the Beta Build
    BetaBuild = "Experimental"

**Comment by patrix87** [comment]
All you have to do is set the BetaBuild variable in your config to "Experimental"

**Comment by Moubai** [comment]
ok thx for the info :D it can be close
