### ISSUE TITLE
Feature request - Oxide update

### ISSUE THREAD

**Issue by jakman76** [patrix87/PowerShellGSM#60]
using the PowerShell for Rust, I'd love to have the Oxide update included or optional.
If not a fit for the official version - I would try adding it myself. Let me know.

Currently using a batch file I run after manual shutdown, would need to integrate this into the PS: 

cd C:\Servers\rustserver\
md serveroxide
bitsadmin /transfer downloadOxide /download /priority normal https://umod.org/games/rust/download?tag=public C:\Servers\rustserver\serveroxide\Oxide-Rust.zip
cd C:\Servers\rustserver\serveroxide
"C:\Program Files\WinRAR\WinRar.exe" x -y Oxide-Rust.zip
:CHECKOXIDE
if exist Oxide-Rust.zip goto DELOXIDE
goto COPYOXIDE
:DELOXIDE
del Oxide-Rust.zip
goto CHECKOXIDE
:COPYOXIDE
xcopy C:\Servers\rustserver\serveroxide C:\Servers\rustserver /e /y
cd C:\Servers\rustserver\
rd /S /Q serveroxide 

thank you.

**Comment by patrix87** [comment]
You could create a RustOxide.psm1 template file to do that.
Some other template also download files during installation.
If you do, please open a Pull Request.
