### ISSUE TITLE
Add Monitoring/Info FNs Documentation

### ISSUE THREAD

**Issue by BananaAcid** [patrix87/PowerShellGSM#66]
Add Documentation about the Monitoring functions, on how to use them manually (from the comandline or from other scripts)

**Comment by patrix87** [comment]
I don't even use those manually.
Would you mind explaining in more detail or provided examples of what you would like to see added to the documentation ?

**Comment by BananaAcid** [comment]
If I recall correctly, I saw monitoring functions in the code, but didn’t dig deeper into it, thought they might be unofficial or just undocumented, but could be used to manage the running instances.
