### ISSUE TITLE
add extra monitoring helpers from fork

### ISSUE THREAD

**Issue by BananaAcid** [patrix87/PowerShellGSM#67]
I found these to be useful to monitor the status of the running servers:

https://github.com/Aeneas1/PowerShellGSM/commit/01e8c807ec4ae8046e07e19a068485ee818304b2
https://github.com/Aeneas1/PowerShellGSM/commit/cba08bb95ece29432e7f5dd3e7597235f38b6c15
https://github.com/Aeneas1/PowerShellGSM/commit/77c4d8ce25d9cdde0abbf8e36ca71c4251734df2
https://github.com/Aeneas1/PowerShellGSM/commit/aedbd5013ee87289ab65343d9c8d4b3ce558cf9b

**Comment by Aeneas1** [comment]
oh that is still WIP, but feel free to use what ever you like.
my plan is to replace the windows tasks cause a server with 5+ gameserver is not useble, with tasks running every 5min.

**Comment by BananaAcid** [comment]
nice @Aeneas1 

Had a similar thought about replacing tasks und  using nssm for adding services (used it in another project as a cheap solution)

What were you thinking about being a solution @Aeneas1

**Comment by Aeneas1** [comment]
i will do it with the monitor thread.
the monitor will check if the a server is alive, need a update or what ever.
so only the monitor is running. then is only 1 windows task needed to check if the monitor is running.
i can try to improve the monitor in the next days.

**Comment by patrix87** [comment]
At this point I was thinking about rewritting the whole thing in C# as an application with a single task-scheduler task to check if it's still alive. That application would take care of monitoring everything.

I clearly don't have the time for that right now though.

**Comment by omayhemo** [comment]
If you do, let a C# service handle the chron jobs, don't use the scheduler.
