### ISSUE TITLE
Updating.

### ISSUE THREAD

**Issue by Haidies-AU** [patrix87/PowerShellGSM#78]
I use this system to run an Ark Survival: Ascended cluster.
Every time there is a large update, the system seems to stop functioning.
After the first detection of the update the log file will end with "Updating  Regular Build."
Each successive check results in "PS>TerminatingError(): "System error.""

I have to go and manually delete the lock file and update each server one by one.

Is there a way to use a download cache?
Update the first map, then copy the install across to the rest.
Or even just use a single install and just run multiple instances?

**Comment by patrix87** [comment]
You can use the same server folder for multiple instances.

Replace the value of $Name by a plain text folder name for the following configuration options:

  #Server Installation Path
  Path                   = ".\servers\$Name"

  #Server configuration folder
  ConfigFolder           = ".\servers\$Name\ShooterGame\Saved\Config\WindowsServer"

  #Server Executable
  Exec                   = ".\servers\$Name\ShooterGame\Binaries\Win64\ArkAscendedServer.exe"

Disable backups and auto-update for all but the main instance.
Set UsePID to $false in the main instance in order for the launcher to close all the instances at once before an update.

**Comment by patrix87** [comment]
No sadly only the main instance will get the warning.

**Comment by Haidies-AU** [comment]
Please forgive the late reply, I have done as recommended, however the main instance is still having issues.
The main instance dosnt shut down the other instances. Main instance UsePID is set to $false.
The main instance starts to update, then for some reason stops.
At every scheduled Task check the main instance then returns *Script error*
I then have to manually delete the .LOCK file, Manually end all instances then start the main instance first, once its finished and loaded THEN start the other instances.
