### ISSUE TITLE
Process is locked, exiting.

### ISSUE THREAD

**Issue by hammondses** [patrix87/PowerShellGSM#8]
Hi there

Have a strange issue where the icarus server I setup was working great, but now the script won't run as the process is locked. 

I can't figure out which process it's talking about though.

I've rebooted with no change. 

I just copied my config to another folder and started from scratch with it downloading everything again with no change.

Any help would be greatly appreciated!

```
Start time: 20221222153854
Username: VM\VM
RunAs User: VM\VM
Configuration Name: 
Machine: VM (Microsoft Windows NT 10.0.19045.0)
Host Application: powershell.exe -noprofile -executionpolicy bypass -file .\main.ps1 -ServerCfg icarus
Process ID: 2772
PSVersion: 5.1.19041.2364
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.19041.2364
BuildVersion: 10.0.19041.2364
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is .\logs\2022-12-22_15-38-54-icarus.txt
Setting Script Directory as Working Directory...
Working Directory : C:\PowerShellGSM
Finding server IPs...
Server local IP : xxxxxxxx
Server external IP : 2xxxxxxxx
Verifying Dependencies...
Importing Server Configuration...
Process is locked, exiting.
**********************
Command start time: 20221222153857
**********************
PS>TerminatingError(): "System error."
**********************
Windows PowerShell transcript end
End time: 20221222153857
**********************
```

**Comment by Waluijay** [comment]
Only way to fix this for me was to manually delete servername.PID and servername.INI in the /servers folder each time it says Process Locked. Not sure if this could cause damage, but I haven't run into anything after doing this many times.

**Comment by patrix87** [comment]
The process is locked when another script is running in the background to avoid concurrency.

The script is configured to keep the server running no mater what. If you need to change a setting, just modify the file in the configs folder. The script will restart automatically on the next schedule task run.
