### ISSUE TITLE
Script running multiple instances of application

### ISSUE THREAD

**Issue by Lionsharks** [patrix87/PowerShellGSM#80]
We're using GSM to manage Ark Survival Ascended servers. Starting this week we've noticed that the powershell script is running to check if the server is running, and then starting a new instance of the server despite the server already running.

We're running 5 server instances from the same VPS, only one is having this issue. I suspected this might be due to the scheduled job running too regularly and so increased the time in task scheduler but this has not solved the problem.

**Comment by patrix87** [comment]
If you run many instances from the same folder, don't do that. It will prevent proper updates.
