### ISSUE TITLE
simple install script written

### ISSUE THREAD

**Issue by BananaAcid** [patrix87/PowerShellGSM#9]
Hi, for my own usage, I created a small install/setup script that could be run by copy-pasting a single line into a powershell terminal.

You might want to have a look at it.
https://gist.github.com/BananaAcid/1dc9117571967b26ceabc972009137ae

1. downloads the current PowerShellGSM scripts (no git needed) with a one-liner
2. allows to update the previously installed PowerShellGSM scripts
3. allows the selection of a server template by arrow keys + enter

rerunning the script allows to activate more templates and updating of the PowerShellGSM files

**Comment by patrix87** [comment]
Nice, thanks, I'll try it and might add it to the readme

**Comment by BananaAcid** [comment]
Update: added a readme with usage info

**Comment by patrix87** [comment]
I added a reference to your script to the readme.
Thanks again.

**Comment by BananaAcid** [comment]
Updated: Added PowershellGSM Version selection for installation (before, it did always install the HEAD)
